//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRAMO.FB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificate : ICertificate 
    {
        public Certificate() 
        {
            this.Levels = new HashSet<Level>();
            this.QuestionInforamtions = new HashSet<QuestionInforamtion>();
        }
    
     
        [System.ComponentModel.DataAnnotations.Key]
        public int CertificateID { get; set; }
     
        public string Name { get; set; }
     
        public string Description { get; set; }
     
        public string Notes { get; set; }
     
        public Nullable<bool> IsActive { get; set; }
     
        public Nullable<bool> IsFeatured { get; set; }
    
        public virtual ICollection<Level> Levels { get; set; }
        public virtual ICollection<QuestionInforamtion> QuestionInforamtions { get; set; }
    }
}
