//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRAMO.FB.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientReview : IClientReview 
    {
        [System.ComponentModel.DataAnnotations.Key]
        public int ClientReviewID { get; set; }
        public string Review { get; set; }
        public string ClientName { get; set; }
        public string ClientTitle { get; set; }
        public string ClientPhoto { get; set; }
    }
}
