//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRAMO.FB.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public interface ICertificate
    {
        int CertificateID { get; set; }
        string Name { get; set; }
        string Description { get; set; }
        string Notes { get; set; }
        Nullable<bool> IsActive { get; set; }
        Nullable<bool> IsFeatured { get; set; }
        string ProgramOverview { get; set; }
        string Objective { get; set; }
        string ProgramTopics { get; set; }
        string Charterholders { get; set; }
        string Candidates { get; set; }
        string Duration { get; set; }
        string Time { get; set; }
    
    }
}
