//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRAMO.FB.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public interface IInstructor
    {
        int InstructorsID { get; set; }
        string Name { get; set; }
        string Position { get; set; }
        string PhotoUrl { get; set; }
        string Summary { get; set; }
    
    }
}
