//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRAMO.FB.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instructor : IInstructor 
    {
        public Instructor() 
        {
            this.Certificates = new HashSet<Certificate>();
        }
    
        [System.ComponentModel.DataAnnotations.Key]
        public int InstructorsID { get; set; }
        public string Name { get; set; }
        public string Position { get; set; }
        public string PhotoUrl { get; set; }
        public string Summary { get; set; }
    
        public virtual ICollection<Certificate> Certificates { get; set; }
    }
}
