//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRAMO.FB.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public interface IOffer
    {
        int OffersID { get; set; }
        string Detail { get; set; }
        string image { get; set; }
        Nullable<bool> IsActive { get; set; }
        Nullable<System.DateTime> Date { get; set; }
        string Title { get; set; }
    
    }
}
