//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRAMO.FB.Data
{
    using System;
    using System.Collections.Generic;
    
    public interface IQuestion
    {
        int QuestionID { get; set; }
        Nullable<int> QuestionInformationID { get; set; }
        string Text { get; set; }
        string Justification { get; set; }
        Nullable<double> ExpectedDuration { get; set; }
        Nullable<int> Weight { get; set; }
        string Notes { get; set; }
        Nullable<int> ParentID { get; set; }
        Nullable<int> ParentTypeID { get; set; }
        Nullable<int> QuestionPoolID { get; set; }
    
    }
}
