//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRAMO.FB.Data
{
    using System;
    using System.Collections.Generic;
    
    public interface IQuestionOption
    {
        int QuestionOptionID { get; set; }
        Nullable<int> QuestionID { get; set; }
        string Text { get; set; }
        string Notes { get; set; }
        Nullable<bool> IsAnswer { get; set; }
    
    }
}
