//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRAMO.FB.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public interface IShareHolder
    {
        int ShareHolderID { get; set; }
        string Name { get; set; }
        string Title { get; set; }
        string Summary { get; set; }
        string PhotoUrl { get; set; }
        string FacebookUrl { get; set; }
        string TwitterUrl { get; set; }
        string GooglePlusUrl { get; set; }
        string LinkedInUrl { get; set; }
        Nullable<bool> IsCEO { get; set; }
        Nullable<int> Rank { get; set; }
    
    }
}
