//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRAMO.FB.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public interface IStudySession
    {
        int StudySessionID { get; set; }
        Nullable<int> SubjectID { get; set; }
        string Name { get; set; }
        string Description { get; set; }
        string Notes { get; set; }
    
    }
}
