//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRAMO.FB.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Microsoft.AspNet.Identity.EntityFramework;
    using System.Data.Entity.ModelConfiguration.Conventions;
    using eRAMO.FB.Data.Identity;
    using eRAMO.FB.Data.Model;
    
    public partial class FBEntities : IdentityDbContext<User, UserRole, int, User_Login, User_UserRole, User_Claim>
    {
        public FBEntities()
            : base("name=FBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
    
            
            modelBuilder.Entity<User>().ToTable("idt.User").Property(p => p.Id).HasColumnName("UserID");
    
            modelBuilder.Entity<User_UserRole>().ToTable("idt.User_UserRole").Property(p => p.RoleId).HasColumnName("UserRoleID");
            modelBuilder.Entity<User_UserRole>().ToTable("idt.User_UserRole").Property(p => p.UserId).HasColumnName("UserID");
    
            modelBuilder.Entity<User_Login>().ToTable("idt.User_Login").Property(p => p.UserId).HasColumnName("UserID");
    
            modelBuilder.Entity<User_Claim>().ToTable("idt.User_Claim").Property(p => p.Id).HasColumnName("User_ClaimID");
            modelBuilder.Entity<User_Claim>().ToTable("idt.User_Claim").Property(p => p.UserId).HasColumnName("UserID");
    
            modelBuilder.Entity<UserRole>().ToTable("idt.UserRole").Property(p => p.Id).HasColumnName("UserRoleID");
        }
    
        public static FBEntities Create()
        {
            return new FBEntities();
        }
        public virtual DbSet<Certificate> Certificates { get; set; }
        public virtual DbSet<Level> Levels { get; set; }
        public virtual DbSet<ParentType> ParentTypes { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<QuestionInforamtion> QuestionInforamtions { get; set; }
        public virtual DbSet<QuestionOption> QuestionOptions { get; set; }
        public virtual DbSet<QuestionPool> QuestionPools { get; set; }
        public virtual DbSet<Reading> Readings { get; set; }
        public virtual DbSet<ShareHolder> ShareHolders { get; set; }
        public virtual DbSet<StudySession> StudySessions { get; set; }
        public virtual DbSet<SubCategory> SubCategories { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<ClientReview> ClientReviews { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Partner> Partners { get; set; }
        public virtual DbSet<Offer> Offers { get; set; }
        public virtual DbSet<CEO> CEOs { get; set; }
        public virtual DbSet<AboutHistory> AboutHistories { get; set; }
    }
}
