//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRAMO.FB.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class News : INews 
    {
        [System.ComponentModel.DataAnnotations.Key]
        public int NewsID { get; set; }
        public string Text { get; set; }
        public string BannarPhoto { get; set; }
        public string Icon { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
