//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRAMO.FB.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer : IOffer 
    {
        [System.ComponentModel.DataAnnotations.Key]
        public int OffersID { get; set; }
        public string Detail { get; set; }
        public string image { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Title { get; set; }
    }
}
