//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRAMO.FB.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner : IPartner 
    {
        [System.ComponentModel.DataAnnotations.Key]
        public int PartnerID { get; set; }
        public string Imge { get; set; }
        public string Text { get; set; }
    }
}
