//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRAMO.FB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question : IQuestion 
    {
        public Question() 
        {
            this.QuestionOptions = new HashSet<QuestionOption>();
        }
    
     
        [System.ComponentModel.DataAnnotations.Key]
        public int QuestionID { get; set; }
     
        public Nullable<int> QuestionInformationID { get; set; }
     
        public string Text { get; set; }
     
        public string Justification { get; set; }
     
        public Nullable<double> ExpectedDuration { get; set; }
     
        public Nullable<int> Weight { get; set; }
     
        public string Notes { get; set; }
     
        public Nullable<int> ParentID { get; set; }
     
        public Nullable<int> ParentTypeID { get; set; }
     
        public Nullable<int> QuestionPoolID { get; set; }
    
        public virtual ParentType ParentType { get; set; }
        public virtual QuestionInforamtion QuestionInforamtion { get; set; }
        public virtual QuestionPool QuestionPool { get; set; }
        public virtual ICollection<QuestionOption> QuestionOptions { get; set; }
    }
}
