//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRAMO.FB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionOption : IQuestionOption 
    {
     
        [System.ComponentModel.DataAnnotations.Key]
        public int QuestionOptionID { get; set; }
     
        public Nullable<int> QuestionID { get; set; }
     
        public string Text { get; set; }
     
        public string Notes { get; set; }
     
        public Nullable<bool> IsAnswer { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
