//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRAMO.FB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reading : IReading 
    {
        public Reading() 
        {
            this.SubCategories = new HashSet<SubCategory>();
        }
    
     
        [System.ComponentModel.DataAnnotations.Key]
        public int ReadingID { get; set; }
     
        public Nullable<int> StudySessionID { get; set; }
     
        public string Name { get; set; }
     
        public string Description { get; set; }
     
        public string Notes { get; set; }
    
        public virtual StudySession StudySession { get; set; }
        public virtual ICollection<SubCategory> SubCategories { get; set; }
    }
}
