//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRAMO.FB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject : ISubject 
    {
        public Subject() 
        {
            this.StudySessions = new HashSet<StudySession>();
        }
    
     
        [System.ComponentModel.DataAnnotations.Key]
        public int SubjectID { get; set; }
     
        public Nullable<int> LevelID { get; set; }
     
        public string Name { get; set; }
     
        public string Description { get; set; }
     
        public string Notes { get; set; }
    
        public virtual Level Level { get; set; }
        public virtual ICollection<StudySession> StudySessions { get; set; }
    }
}
